data:
  batch_size: 64
  dir: MA/data/anomalies/pattern-anomaly
  features:
    - value-0
  name: anomalies.anomalies
  seq_len: 100
  step_size: 1
environment:
  device: !!python/object/apply:torch.device
    - cuda
  is_train: true
  model_path: experiments/uncertainty/anomalies/pattern-anomaly/50-40/window_size_100
  results_path: experiments/uncertainty/anomalies/pattern-anomaly/50-40/window_size_100
  seed: 42
  tensorboard: true
  tensorboard_path: experiments/uncertainty/anomalies/pattern-anomaly/50-40/window_size_100
model:
  dropout: 0.3
  embedding_dim: 40
  hidden_dim:
    - 50
  in_channels: 1
  mode: combined
  name: LSTMAE
test:
  mc_samples: 100
  model_name: ''
  step_size: 1
train:
  early_stopping_threshold: 3
  epochs: 250
  learning_rate: 0.001
