data:
  batch_size: 1
  dir: data/sine/sine-noise-10%
  features:
    - value-0
  name: sine.sine
  seq_len: 10
  step_size: 1
environment:
  device: !!python/object/apply:torch.device
    - cpu
  gpu: 0
  is_train: true
  model_path: experiments/uncertainty/sine/sine-noise-10%/50-40/window_size_10
  results_path: experiments/uncertainty/sine/sine-noise-10%/50-40/window_size_10
  seed: 42
  tensorboard: true
  tensorboard_path: experiments/uncertainty/sine/sine-noise-10%/50-40/window_size_10
model:
  dropout: 0.3
  embedding_dim: 40
  hidden_dim:
    - 50
  in_channels: 1
  mode: combined
  name: LSTMAE
test:
  mc_samples: 100
  model_name: ''
  step_size: 1
train:
  epochs: 100
  learning_rate: 0.001
